import Link from 'next/link';

const products=[
 {name:'MT5 EA #1',type:'MetaTrader 5',desc:'Systematic automated trading strategy. Performance documented with historical testing.',slug:'mt5-ea-1'},
 {name:'MT5 EA #2',type:'MetaTrader 5',desc:'Automated execution model designed for systematic traders.',slug:'mt5-ea-2'},
 {name:'TradingView Strategy',type:'TradingView',desc:'A systematic TradingView strategy built for disciplined analysis.',slug:'tradingview-strategy'}
];

export default function Home(){return <main>
 <header className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'22px 0'}}><Link href="/" style={{fontWeight:800,fontSize:20,textDecoration:'none',color:'#101426'}}>TAHITIAN <span className="gradient">TRADER</span></Link><nav style={{display:'flex',gap:24}}><Link href="/products">Products</Link><Link href="/performance">Performance</Link><Link href="/resources">Resources</Link><Link href="/pricing">Pricing</Link><Link href="/login">Login</Link></nav></header>
 <section className="container" style={{padding:'100px 0 80px',maxWidth:1180}}><div style={{maxWidth:800}}><p style={{fontWeight:700,color:'#7657d9'}}>ALGORITHMIC TRADING TECHNOLOGY</p><h1 style={{fontSize:'clamp(48px,7vw,82px)',lineHeight:1.02,margin:'16px 0'}}>Algorithmic Trading.<br/><span className="gradient">Built with Data.</span></h1><p style={{fontSize:20,lineHeight:1.7,color:'#667085',maxWidth:680}}>Systematic trading algorithms, MetaTrader 5 Expert Advisors and TradingView strategies — documented, measured and built for disciplined traders.</p><div style={{display:'flex',gap:12,marginTop:30}}><Link className="btn btn-primary" href="/products">Explore Products →</Link><Link className="btn btn-secondary" href="/performance">View Performance</Link></div></div></section>
 <section className="container" style={{padding:'50px 0'}}><h2 style={{fontSize:40}}>Featured Products</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:18,marginTop:25}}>{products.map(p=><article className="card" style={{padding:25}} key={p.slug}><small style={{color:'#7657d9',fontWeight:700}}>{p.type.toUpperCase()}</small><h3 style={{fontSize:24}}>{p.name}</h3><p style={{color:'#667085',lineHeight:1.6}}>{p.desc}</p><Link href={'/products/'+p.slug}>View product →</Link></article>)}</div></section>
 <section style={{background:'#101426',color:'white',marginTop:80}}><div className="container" style={{padding:'80px 0'}}><p style={{color:'#a78bfa',fontWeight:700}}>MEASURED, NOT MARKETED</p><h2 style={{fontSize:42,maxWidth:700}}>Backtests and Monte Carlo analysis, presented with context.</h2><p style={{color:'#aeb4c5',maxWidth:650,lineHeight:1.7}}>We separate historical backtests from forward and live results. No fabricated performance figures. Every published result includes methodology and risk context.</p><Link className="btn" style={{background:'white',color:'#101426',marginTop:18}} href="/performance">Explore Performance</Link></div></section>
 <footer className="container" style={{padding:'45px 0',color:'#667085'}}>© 2026 Tahitian Trader · Algorithmic Trading Technology</footer>
 </main>}
