export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: { Tables: {
    products: { Row: { id:string; slug:string; name:string; platform:string; description:string; price_cents:number; currency:string; published:boolean; created_at:string; stripe_standard_price_id:string|null; stripe_developer_price_id:string|null; stripe_price_id:string|null }; Insert: Partial<Database['public']['Tables']['products']['Row']> & { name:string; platform:string; slug:string }; Update: Partial<Database['public']['Tables']['products']['Row']> };
    product_versions: { Row: { id:string; product_id:string; version:string; release_date:string; ex5_path:string|null; mq5_path:string|null; pine_path:string|null; documentation_path:string|null; created_at:string }; Insert: Partial<Database['public']['Tables']['product_versions']['Row']> & { product_id:string; version:string }; Update: Partial<Database['public']['Tables']['product_versions']['Row']> };
    profiles: { Row: { id:string; display_name:string|null; role:string; created_at:string }; Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id:string }; Update: Partial<Database['public']['Tables']['profiles']['Row']> };
    orders: { Row: { id:string; user_id:string; stripe_checkout_session_id:string|null; stripe_payment_intent_id:string|null; status:string; total_cents:number; currency:string; created_at:string }; Insert: Partial<Database['public']['Tables']['orders']['Row']> & { user_id:string }; Update: Partial<Database['public']['Tables']['orders']['Row']> };
    order_items: { Row: { id:string; order_id:string; product_id:string; quantity:number; unit_price_cents:number; license_type:string|null }; Insert: Partial<Database['public']['Tables']['order_items']['Row']> & { order_id:string; product_id:string }; Update: Partial<Database['public']['Tables']['order_items']['Row']> };
    licenses: { Row: { id:string; user_id:string; product_id:string; order_id:string; license_key:string; license_type:string|null; status:string; created_at:string; expires_at:string|null }; Insert: Partial<Database['public']['Tables']['licenses']['Row']> & { user_id:string; product_id:string; order_id:string }; Update: Partial<Database['public']['Tables']['licenses']['Row']> };
    downloads: { Row: { id:string; user_id:string; license_id:string; version_id:string; file_type:string; downloaded_at:string }; Insert: Partial<Database['public']['Tables']['downloads']['Row']> & { user_id:string; license_id:string; version_id:string; file_type:string }; Update: Partial<Database['public']['Tables']['downloads']['Row']> };
    backtests: { Row: { id:string; product_id:string; title:string; report_path:string|null; metrics:Json; created_at:string }; Insert: Partial<Database['public']['Tables']['backtests']['Row']> & { product_id:string; title:string }; Update: Partial<Database['public']['Tables']['backtests']['Row']> };
    monte_carlo_reports: { Row: { id:string; product_id:string; title:string; report_path:string|null; metrics:Json; created_at:string }; Insert: Partial<Database['public']['Tables']['monte_carlo_reports']['Row']> & { product_id:string; title:string }; Update: Partial<Database['public']['Tables']['monte_carlo_reports']['Row']> };
    site_settings: { Row: { key:string; value:Json; updated_at:string }; Insert: Partial<Database['public']['Tables']['site_settings']['Row']> & { key:string }; Update: Partial<Database['public']['Tables']['site_settings']['Row']> };
  }; };
};
