import { cookies } from 'next/headers';

export type Locale = 'en' | 'fr';

export async function getLocale(): Promise<Locale> {
  const store = await cookies();
  return store.get('tt-locale')?.value === 'fr' ? 'fr' : 'en';
}

const en = {
  nav: { products: 'Products', performance: 'Performance', resources: 'Resources', login: 'Login', signOut: 'Sign out', dashboard: 'Dashboard', explore: 'Explore products', home: 'Tahitian Trader home', openNavigation: 'Open navigation' },
  footer: { terms: 'Terms', privacy: 'Privacy', risk: 'Risk disclaimer' },
  home: { eyebrow: 'Algorithmic trading technology', title1: 'Trading systems.', title2: 'Built to be measured.', copy: 'Premium MetaTrader 5 Expert Advisors and TradingView strategies designed for systematic traders who care about process, evidence and controlled execution.', explore: 'Explore products', evidence: 'See the evidence', private: 'Private delivery', privateText: 'Authenticated product access', measured: 'Measured results', measuredText: 'Backtest and Monte Carlo separated', oneTime: 'One-time purchase', oneTimeText: 'No recurring subscription in V1', lineup: 'The product lineup', lineupTitle: 'Focused tools, not a crowded marketplace.', allProducts: 'View all products', digital: 'V1 · Digital delivery', view: 'View product', preparing: 'Catalog preparation in progress', preparingText: 'The V1 products are configured privately and will appear here once their commercial pricing and publication status are finalized.', marketed: 'Measured, not marketed', performanceTitle: 'Backtests. Monte Carlo. Context.', performanceText: 'Historical, simulated, forward and live evidence stay clearly separated. No fabricated figures. No profit promises. Performance data will be added as it is verified.', explorePerformance: 'Explore performance', detailsFallback: 'Product details will be published with the verified launch information.' },
  products: { eyebrow: 'Tahitian Trader · V1 Store', title1: 'Trading systems.', title2: 'One-time access.', copy: 'Explore the V1 collection of systematic trading tools for MetaTrader 5 and TradingView. Every release shows its platform, delivery format and price before you buy.', oneTime: 'One-time purchase', oneTimeText: 'No subscription or recurring fee.', delivery: 'Digital delivery', deliveryText: 'Access your purchased files from your account.', pricing: 'Clear pricing', pricingText: 'The displayed price is the V1 purchase price.', collection: 'The collection', choose: 'Choose your system.', intro: 'Read the dedicated product page for methodology, compatibility, delivery and performance evidence before checkout.', fallback: 'Product details are available on the dedicated product page.', view: 'View product', prepared: 'Products are being prepared.', preparedText: 'The V1 catalog is configured privately and will appear here when published.', pricingTitle: 'Simple by design.', pricingText: 'The initial launch keeps the offer deliberately simple: individual products, one-time payment and digital delivery. Subscriptions, bundles, coupons and additional tiers are reserved for future versions.' },
  performance: { eyebrow: 'Performance', title: 'Evidence before claims.', intro: 'Backtests, Monte Carlo analysis, forward tests and live results stay separate. Only supplied and verified data is published.', net: 'Net profit', win: 'Win rate', drawdown: 'Max drawdown', factor: 'Profit factor', awaiting: 'Awaiting verified data', historical: '01 · Historical', backtests: 'Backtests', noBacktests: 'No backtest reports published yet.', robustness: '02 · Robustness', monte: 'Monte Carlo', noMonte: 'No Monte Carlo reports published yet.', verified: 'Verified data will be added when the reports are published.', risk: 'Risk disclosure', riskText: 'Historical or simulated results are not guarantees of future performance. Execution, spreads, slippage, liquidity and market conditions can materially change real results.' },
  resources: { eyebrow: 'Resources', title1: 'Everything around', title2: 'the systems.', copy: 'A practical knowledge hub for installation, product information, performance methodology and the questions that matter before and after a purchase.', open: 'Open resource', items: [['Getting started', 'How to access a purchase, download your file and move from checkout to your dashboard.'], ['Product documentation', 'Platform compatibility, delivery format and the information you need before installing a release.'], ['Performance methodology', 'How backtests, Monte Carlo analysis, forward testing and live results are presented separately.'], ['FAQ & support', 'Common questions about purchases, licensing, downloads and account access.'], ['Risk disclosure', 'Important information about automated trading, historical results and market risk.']] },
  product: { back: '← Back to products', platform: 'Platform', version: 'Version', release: 'Release', receive: 'What you receive', included: 'Included', noFile: 'No downloadable file is associated with this version yet.', evidence: 'Performance evidence', evidenceText: 'Verified backtests and Monte Carlo results will be displayed here when published. Simulated results remain clearly separated from forward testing and live performance.', secure: 'Secure delivery', secureText: 'Files stay in private Supabase Storage and are delivered through temporary signed URLs after authenticated purchase verification.', access: 'One-time access', own: 'Own this release.', pending: 'Price pending', checkoutPending: 'Checkout will activate once the commercial price is configured.', risk: 'Risk notice', riskText: 'Trading involves risk. Historical or simulated performance is not a guarantee of future results.', ex5: 'MetaTrader 5 Expert Advisor (.ex5)', pine: 'TradingView source (.pine)', docs: 'Documentation', commercialFallback: 'Commercial and technical details will be published with the verified product release.' }
} as const;

const fr = {
  nav: { products: 'Produits', performance: 'Performances', resources: 'Ressources', login: 'Connexion', signOut: 'Déconnexion', dashboard: 'Tableau de bord', explore: 'Voir les produits', home: 'Accueil Tahitian Trader', openNavigation: 'Ouvrir la navigation' },
  footer: { terms: 'Conditions', privacy: 'Confidentialité', risk: 'Avertissement risques' },
  home: { eyebrow: 'Technologie de trading algorithmique', title1: 'Des systèmes de trading.', title2: 'Conçus pour être mesurés.', copy: 'Des Expert Advisors MetaTrader 5 et stratégies TradingView premium conçus pour les traders systématiques qui privilégient le processus, les preuves et une exécution maîtrisée.', explore: 'Voir les produits', evidence: 'Voir les preuves', private: 'Livraison privée', privateText: 'Accès aux produits authentifié', measured: 'Résultats mesurés', measuredText: 'Backtest et Monte Carlo séparés', oneTime: 'Achat unique', oneTimeText: 'Aucun abonnement récurrent en V1', lineup: 'La gamme de produits', lineupTitle: 'Des outils ciblés, pas une marketplace surchargée.', allProducts: 'Voir tous les produits', digital: 'V1 · Livraison numérique', view: 'Voir le produit', preparing: 'Catalogue en préparation', preparingText: 'Les produits V1 sont configurés en privé et apparaîtront ici une fois leur tarification et leur publication finalisées.', marketed: 'Mesuré, pas survendu', performanceTitle: 'Backtests. Monte Carlo. Contexte.', performanceText: 'Les données historiques, simulées, forward et live restent clairement séparées. Aucun chiffre inventé, aucune promesse de rendement. Les données de performance seront ajoutées une fois vérifiées.', explorePerformance: 'Voir les performances', detailsFallback: 'Les détails du produit seront publiés avec les informations de lancement vérifiées.' },
  products: { eyebrow: 'Tahitian Trader · Boutique V1', title1: 'Des systèmes de trading.', title2: 'Accès à l’unité.', copy: 'Découvrez la collection V1 d’outils de trading systématique pour MetaTrader 5 et TradingView. Chaque produit indique sa plateforme, son format de livraison et son prix avant l’achat.', oneTime: 'Achat unique', oneTimeText: 'Aucun abonnement ni frais récurrent.', delivery: 'Livraison numérique', deliveryText: 'Accédez à vos fichiers achetés depuis votre compte.', pricing: 'Tarification claire', pricingText: 'Le prix affiché correspond au prix d’achat V1.', collection: 'La collection', choose: 'Choisissez votre système.', intro: 'Consultez la page dédiée pour la méthodologie, la compatibilité, la livraison et les preuves de performance avant le paiement.', fallback: 'Les détails du produit sont disponibles sur sa page dédiée.', view: 'Voir le produit', prepared: 'Produits en préparation.', preparedText: 'Le catalogue V1 est configuré en privé et apparaîtra lors de sa publication.', pricingTitle: 'Simple par conception.', pricingText: 'Le lancement initial reste volontairement simple : produits individuels, paiement unique et livraison numérique. Les abonnements, bundles, coupons et niveaux supplémentaires sont réservés aux versions futures.' },
  performance: { eyebrow: 'Performances', title: 'Les preuves avant les promesses.', intro: 'Backtests, analyses Monte Carlo, forward tests et résultats live restent séparés. Seules les données fournies et vérifiées sont publiées.', net: 'Profit net', win: 'Taux de réussite', drawdown: 'Drawdown max.', factor: 'Profit factor', awaiting: 'Données vérifiées en attente', historical: '01 · Historique', backtests: 'Backtests', noBacktests: 'Aucun rapport de backtest publié pour le moment.', robustness: '02 · Robustesse', monte: 'Monte Carlo', noMonte: 'Aucun rapport Monte Carlo publié pour le moment.', verified: 'Les données vérifiées seront ajoutées lors de la publication des rapports.', risk: 'Avertissement risques', riskText: 'Les résultats historiques ou simulés ne garantissent pas les performances futures. L’exécution, les spreads, le slippage, la liquidité et les conditions de marché peuvent modifier sensiblement les résultats réels.' },
  resources: { eyebrow: 'Ressources', title1: 'Tout autour de', title2: 'nos systèmes.', copy: 'Un centre de connaissances pratique pour l’installation, les informations produits, la méthodologie de performance et les questions importantes avant et après un achat.', open: 'Ouvrir la ressource', items: [['Bien démarrer', 'Comment accéder à un achat, télécharger votre fichier et passer du paiement à votre tableau de bord.'], ['Documentation produit', 'Compatibilité, format de livraison et informations nécessaires avant d’installer une version.'], ['Méthodologie de performance', 'Comment les backtests, analyses Monte Carlo, forward tests et résultats live sont présentés séparément.'], ['FAQ & support', 'Questions fréquentes sur les achats, licences, téléchargements et accès au compte.'], ['Avertissement risques', 'Informations importantes sur le trading automatisé, les résultats historiques et le risque de marché.']] },
  product: { back: '← Retour aux produits', platform: 'Plateforme', version: 'Version', release: 'Sortie', receive: 'Ce que vous recevez', included: 'Inclus', noFile: 'Aucun fichier téléchargeable n’est encore associé à cette version.', evidence: 'Preuves de performance', evidenceText: 'Les backtests vérifiés et résultats Monte Carlo seront affichés ici une fois publiés. Les résultats simulés restent clairement séparés des tests forward et des performances live.', secure: 'Livraison sécurisée', secureText: 'Les fichiers restent dans Supabase Storage privé et sont livrés via des URLs temporaires signées après vérification d’un achat authentifié.', access: 'Accès à l’unité', own: 'Obtenez cette version.', pending: 'Prix à venir', checkoutPending: 'Le paiement sera activé lorsque le prix commercial sera configuré.', risk: 'Avertissement risques', riskText: 'Le trading comporte des risques. Les performances historiques ou simulées ne garantissent pas les résultats futurs.', ex5: 'Expert Advisor MetaTrader 5 (.ex5)', pine: 'Source TradingView (.pine)', docs: 'Documentation', commercialFallback: 'Les détails commerciaux et techniques seront publiés avec les informations produit vérifiées.' }
} as const;

const translations = { en, fr } as const;

export function getTranslations(locale: Locale) {
  return translations[locale];
}
